cheesetheday/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('', views.Home.as_view(), name="home"),
    path('about/', views.About.as_view(), name="about"),
    path('cheeses/', views.CheeseList.as_view(), name="cheeses"),
    path('cheese/new/', views.CheeseCreate.as_view(), name="cheese_create"),
    path('cheese/<int:pk>', views.CheeseDetail.as_view(), name="cheese_detail"),
    path('cheese/<int:pk>/update/', views.CheeseUpdate.as_view(), name="cheese_update"),
    path('cheese/<int:pk>/delete/', views.CheeseDelete.as_view(), name="cheese_delete"),
    
    path('user/<username>/', views.profile, name="profile"),

    path('wines/', views.WineList.as_view(), name='wines'),
    path('wine/<int:pk>', views.WineDetail.as_view(), name='wine_detail'),
    path('wine/create/', views.WineCreate.as_view(), name='wine_create'),
    path('wine/<int:pk>/update/', views.WineUpdate.as_view(), name='wine_update'),
    path('wine/<int:pk>/delete/', views.WineDelete.as_view(), name='wine_delete'),

    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User


WINE_CHOICES = (
    ("red", "red"),
    ("white", "white"),
    ("rose", "rose"),
    ("sparkling", "sparkling")
)

SWEETNESS = (
    ("dry", "dry"),
    ("medium", "medium"),
    ("sweet", "sweet")
)

class Wine(models.Model):
    name = models.CharField(max_length = 200)
    type = models.CharField(max_length = 20, choices = WINE_CHOICES)
    sweetness = models.CharField(max_length = 100, choices = SWEETNESS)
    
    def __str__(self):
        return self.name 

MILK_CHOICES = (
    ("cow", "cow"),
    ("sheep", "sheep"),
    ("goat", "goat")
)

TYPE_CHOICES = (
    ("fresh","fresh"),
    ("soft", "soft"),
    ("semi-firm", "semi-firm"),
    ("hard", "hard"),
    ("blue", "blue")
)

# Create your models here.
class Cheese(models.Model):
    name = models.CharField(max_length=100)
    img = models.CharField(max_length = 250)
    type = models.CharField(max_length=100, choices=TYPE_CHOICES)
    milk = models.CharField(max_length=100, choices = MILK_CHOICES)
    origin = models.CharField(max_length=100)
    wine = models.ManyToManyField(Wine)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.name

    class Meta: 
        ordering = ['name']

main_app/views.py
from django.shortcuts import render
from django.views import View 
from django.views.generic import DetailView
from django.views.generic.base import TemplateView
from django.views.generic.edit import DeleteView, CreateView, UpdateView
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse 
from .models import Cheese, Wine 
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator 

# Create your views here.

class Home(TemplateView): 
    template_name = "home.html"

class About(TemplateView):
    template_name = "about.html"

# class Cheese: 
#     def __init__ (self, name, type, milk):
#         self.name = name 
#         self.type = type
#         self.milk = milk 

# cheeses = [
#     Cheese("Burrata", "fresh", "cow"), 
#     Cheese("Mozzarella", "fresh", "cow"), 
#     Cheese("Feta", "fresh", "goat"),
#     Cheese("Brie", "soft", "cow"),
#     Cheese("Camembert", "soft", "cow"),
#     Cheese("Havarti", "semi-soft", "cow"),
#     Cheese("Muenster", "semi-soft", "cow"),
#     Cheese("Cheddar", "semi-firm", "cow"),
#     Cheese("Gouda", "semi-firm", "cow"),
#     Cheese("Gruyere", "semi-firm", "cow"),
#     Cheese("Asiago", "hard", "cow"), 
#     Cheese("Manchego", "hard", "cow" ),
#     Cheese("Parmesan", "hard", "cow"),
#     Cheese("Pecorino", "hard", "sheep"),
#     Cheese("Gorgonzola", "blue", "cow" ),
#     Cheese("Roquefort", "blue", "sheep" ),
# ]

class CheeseList(TemplateView):
    template_name = "cheese.html"
    def get_context_data(self,**kwargs): 
        context = super().get_context_data(**kwargs)
        name = self.request.GET.get("name")
        if name != None: 
            context["cheeses"] = Cheese.objects.filter(name__icontains=name)
            context["header"] = f"Search result for {name}:"
        else:
            context['cheeses'] = Cheese.objects.all()
            context['header'] = "List of Cheeses"
        return context

@method_decorator(login_required, name='dispatch')
class CheeseCreate(CreateView): 
    model = Cheese
    fields = ['name', 'type', 'milk', 'origin', 'img', 'wine']
    template_name="cheese_create.html"
    def form_valid(self, form): 
        self.object = form.save(commit=False)
        self.object.user= self.request.user
        self.object.save()
        return HttpResponseRedirect('/cheeses/')

class CheeseDetail(DetailView):
    model = Cheese
    template_name = "cheese_detail.html"

@method_decorator(login_required, name='dispatch')
class CheeseUpdate(UpdateView):
    model = Cheese
    fields = ['name', 'type', 'milk', 'origin', 'img', 'wine']
    template_name = "cheese_update.html"
    def get_success_url(self):
        return reverse('cheese_detail', kwargs={'pk': self.object.pk})

@method_decorator(login_required, name='dispatch')
class CheeseDelete(DeleteView): 
    model = Cheese
    template_name = "cheese_delete_confirm.html"
    success_url = "/cheeses/"

@login_required
def profile(request, username): 
    user = User.objects.get(username=username)
    cheeses = Cheese.objects.filter(user=user)
    return render(request, 'profile.html', {'username': username, 'cheeses': cheeses})

class WineList(TemplateView):
    template_name = "wine_list.html"
    def get_context_data(self,**kwargs): 
        context = super().get_context_data(**kwargs)
        context['wines'] = Wine.objects.all()
        return context

class WineDetail(DetailView):
    model = Wine
    template_name = "wine_detail.html"

@method_decorator(login_required, name='dispatch')
class WineCreate(CreateView):
    model = Wine
    fields = ['name', 'type', 'sweetness']
    template_name = "wine_form.html"
    success_url = '/wines'

@method_decorator(login_required, name='dispatch')
class WineUpdate(UpdateView):
    model = Wine
    fields = ['name', 'type', 'sweetness']
    template_name = "wine_update.html"
    success_url = '/wines'

@method_decorator(login_required, name='dispatch')
class WineDelete(DeleteView):
    model = Wine
    template_name = "wine_confirm_delete.html"
    success_url = '/wines'

# def login_view(request): 
#     if request.method == 'POST':
#         form = AuthenticationForm(request, request.POST)
#         if form.is_valid():
#             u = form.cleaned_data['username']
#             p = form.cleaned_data['password']
#             user = authenticate (username = u, password = p )
#             if user is not None: 
#                 if user.is_active: 
#                     login(request,user)
#                     return HttpResponseRedirect('/user/'+u)
#                 else: 
#                     print('The account has been disabled')
#             else:
#                 print('The username and/or password is incorrect')
#     else: 
#         form = AuthenticationForm()
#         return render(request, 'login.html', {'form': form}) #putting the form inside an object or dictionary

def login_view(request):
    # if POST, then authenticate the user (submitting the username and password)
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            u = form.cleaned_data['username']
            p = form.cleaned_data['password']
            user = authenticate(username = u, password = p)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/user/'+u)
                else:
                    print('The account has been disabled')
                    return HttpResponseRedirect('/login')
        else: 
            return render(request, 'login.html', {'form': form})

    else:
        # user is going to the login page
        form = AuthenticationForm()
        return render(request, 'login.html', {'form': form})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/cheeses')

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid(): 
            user = form.save()
            login(request, user)
            print ('Hi', user.username)
            return HttpResponseRedirect('/user/' + str(user.username))
        else:
            return render(request, 'signup.html', {'form': form})

    else:
        form = UserCreationForm()
        return render(request, 'signup.html', {'form': form})

main_app/templates/about.html
{% extends 'base.html' %}

{% block title %}
Cheese the Day
{% endblock %}

{% block content %}
    <h1> About this page</h1>
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/styles.css'%}"/>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Red+Hat+Display:wght@500&display=swap');
    </style>
    <script src="{% static 'scripts/app.js' %}" defer></script>

    <title>
        {% block title %}
        {% endblock %}
    </title>



</head>
<body>
    <nav>
        {% if user.is_authenticated %}
        <span><a href="{% url 'profile' user.username %}">Welcome, {{ user.username }}!</a></span>
        <span> | </span>
        <span><a href="{% url 'logout' %}">Logout</a></span>
        <span> | </span>
        {% else %}
        <span><a href="{% url 'login' %}">Login</a></span>
        <span> | </span>
        <span><a href="{% url 'signup' %}">Sign-Up</a></span>
        {% endif %}
        <span> | </span>
        <a href="/">Home</a>
        <span> | </span>
        <a href="/about">About</a>
        <span> | </span>
        <a href="/cheeses">Cheeses</a>
        <span> | </span>
        <a href="{%url 'cheese_create' %}"> Add Cheese</a>
        <span> | </span>
        <a href="/wines">Wines</a>
        <span> | </span>
        <a href="{%url 'wine_create' %}"> Add Wine</a>
        <span> | </span>
    </nav>
    {% block content %}
    {% endblock %}
</body>
</html>

main_app/templates/cheese.html
{% extends 'base.html' %}
{% block title %}
List of Cheeses
{% endblock %}

{% block content %}

<div class="cheeseheader">
    <h1> The Ultimate Cheese Guide </h1>
    <h3> A comprehensive listing of various cheese around the world</h3>
</div>

<div class="searchbar">
    <form>
        <div>
            <input type="text" name="name" placeholder="name"/>
            <input type = "submit" value="Search"/>
        </div>
        <a href="{% url 'cheeses' %}">Clear Search</a> 
    </form>
</div>
<br/>
<div class="cheesecontainer">
    <h2>{{header}}</h2>
    <a href="{% url 'cheese_create' %}">Add Cheese</a>
    {% for cheese in cheeses %}
    <div class="cheesebox">
        <h4> Name: {{cheese.name}} </h4>
        <h5> Type: {{cheese.type}} </h5>
        <h5> Milk: {{cheese.milk}} </h5>
        <h5> Country of Origin: {{cheese.origin}} </h5>
        <img src="{{cheese.img}}" alt="picture of {{cheese.name}}">
        <a href="{% url 'cheese_detail' cheese.pk %}">View Details </a>
        <p>Cheese Expert: 
            <a href="/user/{{cheese.user.username}}"> {{cheese.user.username}}</a>
        </p>
    </div>
    {% endfor %}
</div>
{% endblock %}

main_app/templates/cheese_create.html
{% extends 'base.html' %} 
{% block content %}

	<h1>Add New Cheese</h1>
	
	<form method="post">
		  {% csrf_token %} 
		  {{form.as_p}}
		  <input type="submit" value="Submit" />
	</form>
{% endblock %}

main_app/templates/cheese_delete_confirm.html
{% extends 'base.html' %} 

{% block content %}
<h1>Are you sure you want to Delete {{cheese.name}}?</h1>
<form method="post">
  {% csrf_token %}
  <div>
    <input type="submit" value="Confirm" />
    <a href="{% url 'cheese_detail' cheese.pk %}">Cancel</a>
  </div>
</form>
{% endblock %}

main_app/templates/cheese_detail.html
{% extends 'base.html' %} 

{% block content %}

<div>
    <h4> Name: {{cheese.name}} </h4>
    <h5> Type: {{cheese.type}} </h5>
    <h5> Milk: {{cheese.milk}} </h5>
    <h5> Country of Origin: {{cheese.origin}} </h5>
    <img src="{{cheese.img}}" alt="picture of {{cheese.name}}">

    {% for wine in cheese.wine.all %}
    <h4> Good wine pairing: </h4>
        <a href="{% url 'wine_detail' wine.id %}">{{wine.name}}</a>
    {% empty %} 
        <div> No wines yet </div>
    {% endfor %}

</div>
   
<div>
    <a href="{% url 'cheese_update' cheese.pk %}"> Update Cheese Info</a>
    <a href="{% url 'cheese_delete' cheese.pk %}"> Delete </a>
</div>

{% endblock %}

main_app/templates/cheese_update.html
{% extends 'base.html' %} 

{% block content %}
<h1>Update {{cheese.name}}</h1>

<form action="" method="post">
  {% csrf_token %} 
  {{form.as_p}} 
  <input type="submit" value="Submit" />
</form>

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}

{% block title %}
Cheese the Day
{% endblock %}

{% block content %}
    <h1> Cheese the Day </h1>
{% endblock %}

main_app/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

   <h1>Login</h1>
   <form action="" method="post">
       {% csrf_token %}
       {{ form.as_p }}

       <input type="submit" value="Submit">
   </form>

{% endblock %} 

main_app/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>{{ username }}'s collection:</h1>

{% for cheese in cheeses %}
<a href="/cheese/{{ cheese.id }}">
  <h3>{{ cheese.name }}</h3>
</a>

{% endfor %}

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

   <h1>Sign up</h1>
   <form action="" method="post">
       {% csrf_token %}
       {{ form.as_p }}
       <input type="submit" value="Sign up">
   </form>

{% endblock %} 

main_app/templates/wine_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
    <h1>Delete Wine</h1>

    <h4>Are you sure you want to delete <strong>{{wine}}</strong>?</h4>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, delete">
        <a href="{% url 'wine_detail' wine.id %}">Cancel</a>
    </form>

{% endblock %}

main_app/templates/wine_detail.html
<!-- templates/cattoy_show.html -->
{% extends 'base.html' %}
{% block content %}

<h1>Details about {{ wine.name }} </h1>

<div>
    <div>
        <p>Type: {{ wine.type }}</p>
        <p>Sweetness: {{ wine.sweetness }}</p>
        <p> Good cheese pairing: </p>
        {% for cheese in wine.cheese_set.all %}
        <a href=" {% url 'cheese_detail' cheese.id %}"> {{ cheese.name}} </a>
        {% empty %}
            <p> No cheese to pair</p>
        {% endfor %}
    </div>
    <div>
        <a href="{% url 'wine_update' wine.id %}">Edit</a>
        <a href="{% url 'wine_delete' wine.id %}">Delete</a>
    </div>
</div>
{% endblock %}

main_app/templates/wine_update.html
{% extends 'base.html' %} 
{% block content %}

	<h1>Update Wine</h1>
	
	<form method="post">
		  {% csrf_token %} 
          <table>
            {{ form.as_table }}
          </table>
		  <input type="submit" value="Submit" />
	</form>
{% endblock %}